language: julia
os:
  - linux
julia:
  - release
notifications:
  email: false
sudo: required
dist: trusty
addons:
  apt:
     sources:
        - kubuntu-backports
     packages:
        - xorg-dev
        - opencl-headers
        - libglew-dev
        - libosmesa6-dev
        - libgl1-mesa-dev
        - libxcursor-dev
        - libegl1-mesa
        - libpulse-dev
        - libxi-dev
        - libxinerama-dev
        - libxrandr-dev
        - libxss-dev
        - libxt-dev
        - libxv-dev
        - libasound2-dev
        - libudev-dev
        - libgles2-mesa
        - xpra
        - xserver-xorg-video-dummy
        - mesa-utils
        - python-mako
        - python3-mako
before_install:
  - sudo add-apt-repository -y ppa:xorg-edgers/ppa 
  - sudo apt-get update -qq -y
  - export DEBIAN_FRONTEND=noninteractive
  - sudo apt-get -yq --force-yes install libgl1-mesa-dev libgl1-mesa-glx mesa-common-dev libglapi-mesa libgles2-mesa libgles2-mesa-dev libegl1-mesa-dev libgbm1 libgl1-mesa-dri libva1 automake libtool libpthread-stubs0-dev xserver-xorg-dev x11proto-xinerama-dev libx11-xcb-dev libxcb-glx0-dev libxrender-dev xutils-dev xserver-xorg-video-vmware-lts-quantal
  - sudo apt-get -y install linux-headers-$(uname -r)
  - sudo apt-get -yq --force-yes build-dep libgl1-mesa-dri libxcb-glx0-dev
  - export TOP=$PWD
#  - git clone git://anongit.freedesktop.org/git/mesa/mesa
  - git clone git://anongit.freedesktop.org/git/mesa/vmwgfx
  - git clone git://anongit.freedesktop.org/git/mesa/drm
  - git clone git://anongit.freedesktop.org/git/xorg/driver/xf86-video-vmware
  - export LIBDIR=/usr/lib/x86_64-linux-gnu
  - cd $TOP/drm
  - ./autogen.sh --prefix=/usr --libdir=${LIBDIR}
  - make
  - sudo make install
#  - cd $TOP/mesa
#  - ./autogen.sh --prefix=/usr --libdir=${LIBDIR} --with-gallium-drivers=svga --with-dri-drivers=swrast --enable-xa --disable-dri3 --enable-glx-tls
#  - make
#  - sudo make install
  - cd $TOP/xf86-video-vmware
  - ./autogen.sh --prefix=/usr --libdir=${LIBDIR}
  - make
  - sudo make install
  - cd $TOP/vmwgfx
  - make
  - sudo make install
  - sudo depmod -a
  - sudo update-initramfs -u
  - echo vmwgfx | sudo tee -a /etc/modules
  - find /lib/modules -name vmwgfx.ko -exec ls -l '{}' \;
  - sudo modprobe vmwgfx
before_script:
  - "export DISPLAY=:99"
  - xpra --xvfb="Xorg +extension GLX +extension RANDR +extension RENDER -config `pwd`/test/dummy.xorg.conf -logfile ${HOME}/.xpra/xorg.log"  start :99
  - sleep 3 
  - glxinfo | grep -i opengl
  - LIBGL_ALWAYS_SOFTWARE=1 glxinfo | grep OpenGL
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes --depwarn=no -e 'Pkg.clone(pwd()); Pkg.build("GLFW"); Pkg.test("GLFW"; coverage=true)'
